on:
  workflow_dispatch:
    inputs:
      issue_key:
        description: 'Jira Issue Key'
        required: true
        type: string
      comment:
        description: 'Comment from Jira'
        required: false
        type: string
      customfield_10208:
        description: 'Custom Field from Jira'
        required: false
        type: string
      attachments:
        description: 'List of attachments'
        required: true
        type: string
