name: Jira Email Notification

on:
  workflow_dispatch:
    inputs:
      issue_key:
        description: 'Jira Issue Key'
        required: true

jobs:
  notify:
    runs-on: ubuntu-latest
    steps:
      - name: Install Groovy
        run: |
          sudo apt-get update
          sudo apt-get install -y groovy

      - name: Download and Run Groovy Script
        env:
          ISSUE_KEY: ${{ github.event.inputs.issue_key }}
          SMTP_EMAIL: ${{ secrets.SMTP_EMAIL }}
          SMTP_PASSWORD: ${{ secrets.SMTP_PASSWORD }}
        run: |
          curl -O https://raw.githubusercontent.com/<your-username>/<your-repo>/main/scripts/EmailSender.groovy
          groovy scripts/EmailSender.groovy
