name: Handle Jira Attachments

on:
  workflow_dispatch:
    inputs:
      issue_key:
        required: true
        type: string
      attachments:
        required: true
        type: string

jobs:
  process:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v3

      - name: Setup Groovy
        uses: wtfjoke/setup-groovy@v1
        with:
          groovy-version: '4.0.15'

      - name: Run Groovy script
        run: groovy scripts/process_latest_attachments.groovy
        env:
          INPUT_ISSUE_KEY: ${{ github.event.inputs.issue_key }}
          INPUT_ATTACHMENTS: ${{ github.event.inputs.attachments }}
