name: Jira Issue Handler

on:
  repository_dispatch:
    types: [jira_issue_created]

jobs:
  run-issue-handler:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Set up Java (required for Groovy)
        uses: actions/setup-java@v3
        with:
          java-version: '17'

      - name: Install Groovy
        run: |
          sudo apt update
          sudo apt install -y groovy

      - name: Run Groovy Script
        run: groovy handle_issue.groovy payload.json
