name: Jira Changelog Sender

on:
  workflow_dispatch:
    inputs:
      issue_key:
        description: 'Jira Issue Key'
        required: true
      issue_type:
        description: 'Jira Issue Type'
        required: true

jobs:
  send-changelog:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v3

      - name: Install Groovy
        run: |
          sudo apt update
          sudo apt install -y groovy

      - name: Run Groovy Script
        run: groovy scripts/changelog_to_servicenow.groovy "${{ github.event.inputs.issue_key }}" "${{ github.event.inputs.issue_type }}"
