name: Handle Jira Attachments

on:
  workflow_dispatch:
    inputs:
      issue_key:
        description: 'Jira Issue Key'
        required: true
        type: string
      comment:
        description: 'Comment body from Jira'
        required: false
        type: string
      attachments:
        description: 'Attachment JSON string'
        required: true
        type: string

jobs:
  process_attachments:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Set up Java
        uses: actions/setup-java@v3
        with:
          java-version: '17'
          distribution: 'temurin'

      - name: Run Groovy script
        run: groovy scripts/process_latest_attachments.groovy
        env:
          INPUT_ISSUE_KEY: ${{ inputs.issue_key }}
          INPUT_COMMENT: ${{ inputs.comment }}
          INPUT_ATTACHMENTS: ${{ inputs.attachments }}
